image: alpine/edge
packages:
    - python3
    - python3-dev
    - py3-setuptools
    - libc6-compat
    - build-base
    - automake
    - autoconf
    - npm
secrets:
    - c6d81f00-6932-41de-aa13-98667964e111
sources:
    - https://git.sr.ht/~remyabel/linux-guide-and-hints
tasks:
    - setup: |
        cd linux-guide-and-hints
        mkdir -p cert && touch cert/server.key && touch cert/server.crt && touch cert/ca.crt
        pip3 install -U --user sphinx sphinx-sitemap
        npm install --save grunt
        npm install
    - build: |
        cd linux-guide-and-hints
        PATH=/home/build/.local/bin:$PATH
        export PATH
        make html SPHINXOPTS=-Ea
        ./node_modules/grunt/bin/grunt build
    - deploy: |
        set +x
        . ~/GH_TOKEN
        set -x
        git clone --quiet --branch='gh-pages' --depth=1 https://github.com/remyabel/linux-guide-and-hints.git \
            > /dev/null 2>&1
        git config user.email 'deploy@sr.ht'
        git config user.name 'sr.ht deployment bot'
        cp -r ~/linux-guide-and-hints/build/html .
        cp -r ~/linux-guide-and-hints/.nojekyll .
        cp -r ~/linux-guide-and-hints/CNAME .
        git add -A .
        git commit -qm 'Deploy to gh-pages.'
        git push --quiet https://"$GH_TOKEN"@github.com/linux-guide-and-hints.git
