image: alpine/edge
packages:
    - python3
    - python3-dev
    - py3-setuptools
    - libc6-compat
    - build-base
    - automake
    - autoconf
    - npm
secrets:
    - bdbd9992-5ade-44b9-8809-453412699617
sources:
    - https://git.sr.ht/~remyabel/linux-guide-and-hints
tasks:
    - setup: |
        cd linux-guide-and-hints
        mkdir -p cert && touch cert/server.key && touch cert/server.crt && touch cert/ca.crt
        pip3 install -U --user sphinx sphinx-sitemap
        npm install --save grunt
        npm install
    - build: |
        cd linux-guide-and-hints
        PATH=/home/build/.local/bin:$PATH
        export PATH
        make html SPHINXOPTS=-Ea
        ./node_modules/grunt/bin/grunt build
    - deploy: |
        set +x
        . ~/GH_TOKEN
        set -x
        git clone --branch='gh-pages' --depth=1 https://github.com/remyabel/linux-guide-and-hints.git gh-pages
        cd gh-pages
        git config user.email 'deploy@sr.ht'
        git config user.name 'sr.ht deployment bot'
        cp -r ~/linux-guide-and-hints/build/html/* .
        cp -r ~/linux-guide-and-hints/.nojekyll .
        cp -r ~/linux-guide-and-hints/CNAME .
        git add -A .
        git commit -m 'Deploy to gh-pages.'
        # If there was nothing to commit...
        if [[ $? == 1 ]]; then
            echo "Nothing to commit. Skipping deploy."
            # Exit with a good status so the build does not fail
            exit 0
        else
            set +x
            git push https://remyabel:"$GH_TOKEN"@github.com/remyabel/linux-guide-and-hints.git
            set -x
        fi
