language: python
python:
- "2.7"

install:
- pip install sphinx

script:
- make html SPHINXOPTS=-Ea

deploy:
    provider: pages
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}
    fqdn: www.linuxguideandhints.com
    local_dir: build/html
    on:
        branch: master

after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
     -H "X-Auth-Email: ${CF_EMAIL}" \
     -H "X-Auth-Key: ${CF_API_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

notifications:
    email: false
